### ISSUE TITLE
Add Identity claim

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/draft-birkholz-rats-corim#17]
Extend CoMID to carry Identity claims (i.e., key material) that can be associated either with a Class or an (single or group) Instance of a Class.

Requirements:
* Support generic key material;
* Support generic Identifiers with Instance, Class or Batch scope;
* Standards based.

**Comment by nedmsmith** [comment]
For example:
claims-entry = {
? ref-claims => reference-value / [2* reference-value],
? end-claims => endorsed-value / [2* endorsed-value],
? id-claims => identity-value / [2* identity-value],
* $$claims-entry-extension,
}
; device-id is only present if the key material applies
; to a specific instance. Otherwise, the class identifier
; in the element-name defines the scope.
identity-value = {
 ? device-id => device-id-type,
 key-material => COSE_KeySet, ; see RFC8152, draft-ietf-cose-x509
}

device-id-type /= #6.47115(psa-instance-id-type)

**Comment by nedmsmith** [comment]
Is there a #6.4711 for HardwareModuleName as defined in RFC4108 
e.g. HardwareModuleName ::= SEQUENCE {
        hwType OBJECT IDENTIFIER,
        hwSerialNum OCTET STRING }
This might be a reasonable form since existing certificates may be using it.

**Comment by thomas-fossati** [comment]
Closed by #25
