### ISSUE TITLE
Updates relationship type

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats/draft-birkholz-rats-corim#29]
Should we include 'updates' relationship type?

The use case is when a vendor provides an update to a previously released module. Normally, the updated corim will bump the tag-version number but the tag-id will remain the same. A search on tag-id alone would reveal both tags. The highest value tag-version is the current tag. 

The current tag replaces the claims in the previous version tag. I think it is ambiguous whether the entire tag is replaced or just the claims. I'm leaning toward replacing the entire tag. 

Nevertheless, it may be helpful for the new tag to include a link to the previous tag. This would make sense if the Attester points a hint to the previous tag, but discovers an updated tag. Having a pointer to the updated tag helps verifier find claims that have been invalidated and removes them.

There isn't an 'updates' relationship in swid/coswid. There is patch (which isn't a full update) and ancestor with seems to point the other direction - but I might be reading it wrong. I'm proposing using 'updates' for comid since it seems more clear.

**Comment by thomas-fossati** [comment]
A few clarifying question:

> The use case is when a vendor provides an update to a previously released module.

By _"update to a previously released module"_ do you mean updating the content of the Tag - adding or rectifying metadata -, or updating the underlying phy reality (e.g., circuitry and/or embedded FW)?

> Normally, the updated corim will bump the tag-version number but the tag-id will remain the same.

My understanding is this should happen at the CoMID level rather than at the CoRIM?

> A search on tag-id alone would reveal both tags. The highest value tag-version is the current tag.

> The current tag replaces the claims in the previous version tag. I think it is ambiguous whether the entire tag is replaced or just the claims. I'm leaning toward replacing the entire tag.

Yes, semantics of tag-version (if we want CoMID to fully match CoSWID in this respect, which I think is desirable) is that the new version completely obliterates any older version.

> Nevertheless, it may be helpful for the new tag to include a link to the previous tag. This would make sense if the Attester points a hint to the previous tag, but discovers an updated tag. Having a pointer to the updated tag helps verifier find claims that have been invalidated and removes them.

This could be done at the endorsement provisioning step based on existing input (tag-id and tag-version) alone.

> There isn't an 'updates' relationship in swid/coswid. There is patch (which isn't a full update) and ancestor with seems to point the other direction - but I might be reading it wrong. I'm proposing using 'updates' for comid since it seems more clear.

That said, I'm all for `updates` and `patches` relations because I see a clear use case for embedded FW, in which case the semantics is crystal clear.  Less so for the described scenario, where I think the existing mechanics is sufficient.

**Comment by nedmsmith** [comment]
I believe the semantics for 'updates' should be: The new tag contains all the claims from the old tag that are still valid after applying an update to the module / elements. It replaces element-values that changed as a result of the update. It links to the old tag for reasons of audit, chain of custody, verification of vendor's intent to update the old tag. Version or SVN claims are updated. The tag version is updated.

The semantics for 'patches' (I believe) should be: The new tag contains only claims that were changed by applying the patch. The union of the old and new tags is needed to complete the verification. Version (patch level) or SVN claims are updated. (I don't think patches is needed since 'updates' could be used also). The tag version is updated.

Semantics for 'replaces' (aka supersedes) should be: The new tag contains all the claims from the old tag, but corrects the errors that existed in the old tag. The version and SVN do not change. The tag-version doesn't change.

**Comment by nedmsmith** [comment]
a description of proposed relationship types are described in Issue #23
